### PR TITLE
Small fixes for better python3 compatibility

### PR DESCRIPTION
**Pull request by AC130USpectre**

### CODE REVIEW

**Comment by Compro-Prasad** [comment]
@pandusonu2 This looks good

**Comment by pandusonu2** [comment]
@Compro-Prasad added you to the manga-team :)

**Review by Compro-Prasad — CHANGES_REQUESTED** [review]
Two files are still missing `python3` syntax:
1. `fav.py`
2. `newsteller.py`

Apart from that there are some lint errors which you can fix if you want.

**Comment by pandusonu2** [comment]
@Compro-Prasad I think this can be merged, I will check for any other changes while refactoring the repository later on.

**Pull request merged**
