### PR TITLE
PYTHON only: A better `cd` support. Most diffs are due to extra whitespaces.

### PR DESCRIPTION
**Pull request by Compro-Prasad**
I got rid of pep8 linting errors/warnings and extra whitespaces on blank lines.
I also applied some docstrings to some functions. This will help to provide docstrings on auto completion while the comment version wont work.
I suggest that you use some kind of linter to remove extra whitespaces as whenever I would pull your code I would have to run my linter again which would result in much larger diffs in git. This would also reduce file size too.
And please consider using input() and print() as they violate modern linters.
More to come in near future. Man page, gtk support...

### CODE REVIEW

**Comment by pandusonu2** [comment]
Woah thanks for the awesome PR :D I primarily want to focus on BASH script rather than the python part of files. The python part is just for new contributors you can say. Any new change should be implemented in BASH first and PYTHON later!! Strictly!!
As for GTK, do check #4 :) 
Thans for the awesome contributions, will check them in a while.

**Comment by Compro-Prasad** [comment]
Ok, I will try. Have done Qt in C++. Gtk is in C++/python but not in bash. Can try out tcl/tk in wish or tkinter in python but they look legacy in nature.
It would be nice if could mention the language and the library specifically.
I was also thinking of an `install.sh` to move the files as
1. `manga-dl` -> `download.sh`
2. `manga-fav` -> `fav.sh`
3. `manga-news` -> `newsteller.sh`
4. `manga-pg` -> `page.py`
in the standard locations(`/usr/local/bin/`)

**Comment by pandusonu2** [comment]
The language for #4 is C Gtk+3.0 library. I mentioned it in the issue page. Also, I pointed out the plan. 
As for moving into /usr/local/bin/ I wouldn't want to mess with sudo settings just yet, after a little more development :P 
Coming to your PR, I will be checking it tonight, I would add coala linter to it and push my commit first, you might have to rebase later on if I do it. So just commit tonight, I would finish checking and doing necessary steps by tomorrow :) 
You can get started on your Proposal in the mean time after you are done with your commits :)

**Comment by Compro-Prasad** [comment]
Sorry about that. I didn't checkout the issues at first. I just forked cloned and got going.

**Pull request closed without merging**
