### PR TITLE
Fixed #31: Check for the validity of manga name

### LINKED ISSUE #31: Check before adding favourites
When you execute 'bash fav.sh', we add fav titles to a hidden .fav file. But we don't check if the title is valid.
So make changes to fav.sh to check if the title is valid or not before adding it .fav

### PR DESCRIPTION
**Pull request by DarkSouL11**
Now fav.sh checks if the entered manga name is valid before adding it to the fav. list.

### CODE REVIEW

**Comment by pandusonu2** [comment]
Wouldn't it be better to write a function instead of writing same piece of code twice?

**Comment by DarkSouL11** [comment]
@pandusonu2 Done added a function.

**Comment by pandusonu2** [comment]
Will do some testing before I add it. 
Thanks for the contribution :D This is very helpful. 
This opens up whole new use of favourites now :+1:

**Comment by DarkSouL11** [comment]
Ok @pandusonu2

**Comment by pandusonu2** [comment]
@DarkSouL11 Try using 
`curl -Is http://www.mangareader.net/$m | head -1`
for checking the availability of URL :smile: 
Saves you from using index.html which will have the main website in it, and also the log. 
But I'm open to suggestion, if you think wget is better, lemme know.

**Comment by DarkSouL11** [comment]
Completely new to bash, So i didn't know about curl.Curl looks much better and professional, also less code involved so I think curl's better :P

**Comment by pandusonu2** [comment]
We learn new things every day :D 
Curl makes things easier as it directly gives the status of the http request, which gives the status code of the request :grin: 
I prefer you add a `grep 200` to it and just put that in the if condition :)

**Comment by DarkSouL11** [comment]
ok :thumbsup:

**Comment by pandusonu2** [comment]
Can you tell me why you are writing output to /dev/null, I'm not saying its wrong. I just never used it.
I was thinking more like
`if [[ $(curl -s --head http://www.mangareader.net/$m | grep "200" | wc -c) -ne 0 ]]`
wc gets the number of lines and -ne is not equal to 0.

The /dev/null might be good too, just wanted to know what it does.

**Comment by DarkSouL11** [comment]
@pandusonu2 even this 
`curl -s --head http://www.mangareader.net/$m | grep "200 OK"`
would have worked but every time the output of
`curl -s --head http://www.mangareader.net/$m`
was being directed to the stdout so I simply redirected that output to `/dev/null`using `> /dev/null`.

**Comment by pandusonu2** [comment]
Ok :+1: Merged it as it is.
Thank you for your contribution :smile:

**Pull request closed without merging**
