### PR TITLE
Fixes #28 and #38

### LINKED ISSUE #28: Use /latest for getting larger output
The current newsteller parses data from the main site, but using <site>/latest gives us larger data.

### PR DESCRIPTION
**Pull request by chetangargnitd**

### CODE REVIEW

**Review by akshatnitd — APPROVED** [review]
@chetangargnitd Awesome PR! :smile: Can be merged. 
@pandusonu2

**Comment by pandusonu2** [comment]
Thank you for your contribution :) 
But, I can just merge one of the patches, as both are newcomer issues.
I also need you to change the commit message to the following format:
"Fixed #\<issue number\>: commit message"

**Comment by chetangargnitd** [comment]
Done.

**Comment by pandusonu2** [comment]
Ah........ You went wrong somewhere. I can see four commits (-.-)" You need to do some serious rebase.
Ping in the gitter channel.

**Comment by pandusonu2** [comment]
Why did you close this?

**Pull request closed without merging**
