### PR TITLE
Fixes #27: Able to check status of favourites

### LINKED ISSUE #27: Check the status of favourites
Add option to display the status of favourite titles. 

It can display in the form of
\<title\> \<latest chapter release\> \<date of release\>

### PR DESCRIPTION
**Pull request by akshatnitd**
Please check this out! :smile:

### CODE REVIEW

**Comment by pandusonu2** [comment]
Neat commit, but I'm not sure I would want to move to python until someone does Issue #23 first. I would test your PR a bit until then.
Feel free to work on Issue #23 if you have time.
Nothing against python, but it makes things easier, and decreases scope of learning, which you get if the repo is in BASH. 
Even in future, if there are additional features, I would like to make it in BASH first and then port to python.

**Comment by akshatnitd** [comment]
@pandusonu2 Sure. Will be working on #23 :smile:

**Comment by pandusonu2** [comment]
Hahaha, Python makes things so much easier :+1: Will merge it soon.
Thank you for your contribution :grin:

**Comment by akshatnitd** [comment]
@pandusonu2 True that! Python is too awesome :+1:

**Comment by pandusonu2** [comment]
There have been few more changes :) Please incorporate the changes too. I'm keeping this on Hold.
When you have python script for all the files, will merge them one by one :)

**Comment by akshatnitd** [comment]
@pandusonu2 Okay! Doing the needful. And writing the other scripts too :smile:

**Pull request merged**
