### PR TITLE
Added comments to the code

### PR DESCRIPTION
**Pull request by sark01**

### CODE REVIEW

**Comment by pandusonu2** [comment]
Thank you for your contribution @sark01

**Comment by pandusonu2** [comment]
Thank you for your contribution @sark01

**Comment by ananyo2012** [comment]
@sark01  Happy to see your first PR merged :smile:  Just to make aware of the best practices always write a commit message mentioning the issue no and a statement like Fixes #11. That way we will able to link to that issue and it will easier for us to review your PR. Follow this tutorial on how to write good commit messages http://chris.beams.io/posts/git-commit/

**Comment by sark01** [comment]
will keep that in mind, thank you @ananyo2012

**Pull request merged**
