### PR TITLE
Changed code so that index.html opens with firefox

### PR DESCRIPTION
**Pull request by DarkSouL11**

### CODE REVIEW

**Comment by ananyo2012** [comment]
@DarkSouL11 Ok here comes the place for conflict resolution. We will explaining this to you

**Comment by pandusonu2** [comment]
@DarkSouL11 Until we resolve the conflict, please read the issue comments :) 
I would like to advise you to try out this - "Adding an option while executing would be more preferred :D"

Say, executing 'bash page.sh -f' opens firefox and by default, it will open chrome :)
Try that. Thank you for your contribution.

**Comment by DarkSouL11** [comment]
trying that :+1:  @pandusonu2

**Comment by ananyo2012** [comment]
@DarkSouL11 Just wait a bit we will posting a link on conflict resolutions then you can resolve the conflict and move on

**Comment by DarkSouL11** [comment]
ok thanks :) @ananyo2012

**Comment by pandusonu2** [comment]
@DarkSouL11 now that you know merge/conflict/rebase. Do correct this PR :) Drop the first commit and correct the other two commits. 
I want the message of the commits to be of this format:
"Fixes #<issue number>: <Commit message>" 
Use reword while rebase to correct the commit message. 
If you have any doubts, feel free to ping in gitter :)

**Comment by DarkSouL11** [comment]
@pandusonu2 on it.

**Comment by pandusonu2** [comment]
Awesome work @DarkSouL11 
Thank you for your contribution :+1:

**Pull request closed without merging**
